name: Destroy Preview Environment

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          url: ${{secrets.OKTETO_DEMO_URL}}
          token: ${{ secrets.OKTETO_DEMO_TOKEN }}

      - name: Destroy preview environment
        uses: okteto/destroy-preview@latest
        with:
          name: movies-rental-pr-${{ github.event.pull_request.number }}

      